"use strict";
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const config_1 = require("prisma/config");
module.exports = (0, config_1.defineConfig)({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
//# sourceMappingURL=prisma.config.js.map
