/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedVendorStoreRouteImport } from './routes/_authenticated/vendor.store'
import { Route as AuthenticatedVendorProductsRouteImport } from './routes/_authenticated/vendor.products'
import { Route as AuthenticatedVendorPaymentsRouteImport } from './routes/_authenticated/vendor.payments'
import { Route as AuthenticatedVendorOrdersRouteImport } from './routes/_authenticated/vendor.orders'
import { Route as AuthenticatedVendorInvoicesRouteImport } from './routes/_authenticated/vendor.invoices'
import { Route as AuthenticatedVendorDeliveryRouteImport } from './routes/_authenticated/vendor.delivery'
import { Route as AuthenticatedVendorCouponsRouteImport } from './routes/_authenticated/vendor.coupons'
import { Route as AuthenticatedVendorAnalyticsRouteImport } from './routes/_authenticated/vendor.analytics'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin.vendors'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminDeliveryRouteImport } from './routes/_authenticated/admin.delivery'
import { Route as AuthenticatedAdminCommissionRouteImport } from './routes/_authenticated/admin.commission'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated/account.wishlist'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAccountInvoicesRouteImport } from './routes/_authenticated/account.invoices'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account.addresses'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedVendorStoreRoute =
  AuthenticatedVendorStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorProductsRoute =
  AuthenticatedVendorProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorPaymentsRoute =
  AuthenticatedVendorPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorOrdersRoute =
  AuthenticatedVendorOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorInvoicesRoute =
  AuthenticatedVendorInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorDeliveryRoute =
  AuthenticatedVendorDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorCouponsRoute =
  AuthenticatedVendorCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorAnalyticsRoute =
  AuthenticatedVendorAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDeliveryRoute =
  AuthenticatedAdminDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommissionRoute =
  AuthenticatedAdminCommissionRouteImport.update({
    id: '/commission',
    path: '/commission',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountInvoicesRoute =
  AuthenticatedAccountInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/vendors': typeof VendorsRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/invoices': typeof AuthenticatedAccountInvoicesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/commission': typeof AuthenticatedAdminCommissionRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/vendor/analytics': typeof AuthenticatedVendorAnalyticsRoute
  '/vendor/coupons': typeof AuthenticatedVendorCouponsRoute
  '/vendor/delivery': typeof AuthenticatedVendorDeliveryRoute
  '/vendor/invoices': typeof AuthenticatedVendorInvoicesRoute
  '/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/vendor/payments': typeof AuthenticatedVendorPaymentsRoute
  '/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/vendor/store': typeof AuthenticatedVendorStoreRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/vendors': typeof VendorsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/invoices': typeof AuthenticatedAccountInvoicesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/commission': typeof AuthenticatedAdminCommissionRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/vendor/analytics': typeof AuthenticatedVendorAnalyticsRoute
  '/vendor/coupons': typeof AuthenticatedVendorCouponsRoute
  '/vendor/delivery': typeof AuthenticatedVendorDeliveryRoute
  '/vendor/invoices': typeof AuthenticatedVendorInvoicesRoute
  '/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/vendor/payments': typeof AuthenticatedVendorPaymentsRoute
  '/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/vendor/store': typeof AuthenticatedVendorStoreRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/vendors': typeof VendorsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/account/invoices': typeof AuthenticatedAccountInvoicesRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/commission': typeof AuthenticatedAdminCommissionRoute
  '/_authenticated/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/vendor/analytics': typeof AuthenticatedVendorAnalyticsRoute
  '/_authenticated/vendor/coupons': typeof AuthenticatedVendorCouponsRoute
  '/_authenticated/vendor/delivery': typeof AuthenticatedVendorDeliveryRoute
  '/_authenticated/vendor/invoices': typeof AuthenticatedVendorInvoicesRoute
  '/_authenticated/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/_authenticated/vendor/payments': typeof AuthenticatedVendorPaymentsRoute
  '/_authenticated/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/_authenticated/vendor/store': typeof AuthenticatedVendorStoreRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/reset-password'
    | '/search'
    | '/vendors'
    | '/account'
    | '/admin'
    | '/vendor'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/account/addresses'
    | '/account/invoices'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/commission'
    | '/admin/delivery'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendors'
    | '/vendor/analytics'
    | '/vendor/coupons'
    | '/vendor/delivery'
    | '/vendor/invoices'
    | '/vendor/orders'
    | '/vendor/payments'
    | '/vendor/products'
    | '/vendor/store'
    | '/account/'
    | '/admin/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/reset-password'
    | '/search'
    | '/vendors'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/account/addresses'
    | '/account/invoices'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/commission'
    | '/admin/delivery'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendors'
    | '/vendor/analytics'
    | '/vendor/coupons'
    | '/vendor/delivery'
    | '/vendor/invoices'
    | '/vendor/orders'
    | '/vendor/payments'
    | '/vendor/products'
    | '/vendor/store'
    | '/account'
    | '/admin'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/reset-password'
    | '/search'
    | '/vendors'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/vendor'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/_authenticated/account/addresses'
    | '/_authenticated/account/invoices'
    | '/_authenticated/account/orders'
    | '/_authenticated/account/wishlist'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/commission'
    | '/_authenticated/admin/delivery'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/vendor/analytics'
    | '/_authenticated/vendor/coupons'
    | '/_authenticated/vendor/delivery'
    | '/_authenticated/vendor/invoices'
    | '/_authenticated/vendor/orders'
    | '/_authenticated/vendor/payments'
    | '/_authenticated/vendor/products'
    | '/_authenticated/vendor/store'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  VendorsRoute: typeof VendorsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/vendor/store': {
      id: '/_authenticated/vendor/store'
      path: '/store'
      fullPath: '/vendor/store'
      preLoaderRoute: typeof AuthenticatedVendorStoreRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/products': {
      id: '/_authenticated/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof AuthenticatedVendorProductsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/payments': {
      id: '/_authenticated/vendor/payments'
      path: '/payments'
      fullPath: '/vendor/payments'
      preLoaderRoute: typeof AuthenticatedVendorPaymentsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/orders': {
      id: '/_authenticated/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof AuthenticatedVendorOrdersRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/invoices': {
      id: '/_authenticated/vendor/invoices'
      path: '/invoices'
      fullPath: '/vendor/invoices'
      preLoaderRoute: typeof AuthenticatedVendorInvoicesRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/delivery': {
      id: '/_authenticated/vendor/delivery'
      path: '/delivery'
      fullPath: '/vendor/delivery'
      preLoaderRoute: typeof AuthenticatedVendorDeliveryRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/coupons': {
      id: '/_authenticated/vendor/coupons'
      path: '/coupons'
      fullPath: '/vendor/coupons'
      preLoaderRoute: typeof AuthenticatedVendorCouponsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/analytics': {
      id: '/_authenticated/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof AuthenticatedVendorAnalyticsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/delivery': {
      id: '/_authenticated/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commission': {
      id: '/_authenticated/admin/commission'
      path: '/commission'
      fullPath: '/admin/commission'
      preLoaderRoute: typeof AuthenticatedAdminCommissionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/wishlist': {
      id: '/_authenticated/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/invoices': {
      id: '/_authenticated/account/invoices'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AuthenticatedAccountInvoicesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountInvoicesRoute: typeof AuthenticatedAccountInvoicesRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
  AuthenticatedAccountInvoicesRoute: AuthenticatedAccountInvoicesRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCommissionRoute: typeof AuthenticatedAdminCommissionRoute
  AuthenticatedAdminDeliveryRoute: typeof AuthenticatedAdminDeliveryRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCommissionRoute: AuthenticatedAdminCommissionRoute,
  AuthenticatedAdminDeliveryRoute: AuthenticatedAdminDeliveryRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedVendorRouteChildren {
  AuthenticatedVendorAnalyticsRoute: typeof AuthenticatedVendorAnalyticsRoute
  AuthenticatedVendorCouponsRoute: typeof AuthenticatedVendorCouponsRoute
  AuthenticatedVendorDeliveryRoute: typeof AuthenticatedVendorDeliveryRoute
  AuthenticatedVendorInvoicesRoute: typeof AuthenticatedVendorInvoicesRoute
  AuthenticatedVendorOrdersRoute: typeof AuthenticatedVendorOrdersRoute
  AuthenticatedVendorPaymentsRoute: typeof AuthenticatedVendorPaymentsRoute
  AuthenticatedVendorProductsRoute: typeof AuthenticatedVendorProductsRoute
  AuthenticatedVendorStoreRoute: typeof AuthenticatedVendorStoreRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
}

const AuthenticatedVendorRouteChildren: AuthenticatedVendorRouteChildren = {
  AuthenticatedVendorAnalyticsRoute: AuthenticatedVendorAnalyticsRoute,
  AuthenticatedVendorCouponsRoute: AuthenticatedVendorCouponsRoute,
  AuthenticatedVendorDeliveryRoute: AuthenticatedVendorDeliveryRoute,
  AuthenticatedVendorInvoicesRoute: AuthenticatedVendorInvoicesRoute,
  AuthenticatedVendorOrdersRoute: AuthenticatedVendorOrdersRoute,
  AuthenticatedVendorPaymentsRoute: AuthenticatedVendorPaymentsRoute,
  AuthenticatedVendorProductsRoute: AuthenticatedVendorProductsRoute,
  AuthenticatedVendorStoreRoute: AuthenticatedVendorStoreRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
}

const AuthenticatedVendorRouteWithChildren =
  AuthenticatedVendorRoute._addFileChildren(AuthenticatedVendorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedVendorRoute: AuthenticatedVendorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  VendorsRoute: VendorsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
